### ISSUE TITLE
TypeError: dtw() got an unexpected keyword argument 'dist_method'

### ISSUE THREAD

**Issue by jdiazram** [Bill1235813/IVLN#6]
Hi, nice work
I try to run `bash scripts/iter_train_sep_hist_weight.sh`, and this shows me when I finish the iteration:

```
Listener training starts, start iteration: 0
Progress: |██████████████████████████████████████████████████| 99.0% Complete
total_actions 1, max_length 1, entropy 0.0000, IL_loss 1.4613, RL_loss 0.0000, policy_loss 0.0000, critic_loss 0.0000
eval 1011 predictions
Traceback (most recent call last):
  File "r2r/main.py", line 368, in <module>
    main()
  File "r2r/main.py", line 362, in main
    train(args, train_env, val_envs, aug_env=aug_env, rank=rank)
  File "r2r/main.py", line 229, in train
    tour_ndtw = compute_tour_ndtw(edited_pred_path, edited_gt_path, dist_func)
  File "/home/jorge/Documents/IVLN/finetune_src/r2r/eval_utils.py", line 161, in compute_tour_ndtw
    dtw_dist = dtw.dtw(
TypeError: dtw() got an unexpected keyword argument 'dist_method'
```
This is only training, not inference. 

And with `bash scripts/run_r2r_il.sh` and `bash scripts/iter_train.sh` is the same problem.

Did I lose something? Do you know why that is?

Thx

**Comment by Bill1235813** [comment]
Thank you for the question!

Please make sure you install the package ``dtw-python==1.3..0`` not ``dtw``.

I'll update the requirements.

**Comment by jdiazram** [comment]
Thank you!
